name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # Add your build and test steps here

  security_scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup trivy
        uses: aquasecurity/trivy-action@v0.6.0

      - name: Run trivy
        run: trivy --exit-code 1 .

  deploy:
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add your deployment steps here
